feat: Option to center axis tick labels between tick lines
d3fc/d3fc pull request #1231
Opened 2019-02-25 16:49 UTC by DevAndyLee

- `centerAlignTicks` boolean property (defaults to false)
- `tickOffset` function gives a default implementation based on the scale's `step`, but can be overridden to customise behaviour - e.g. for non-evenly-spaced custom scale.
- `labelOffset` should not include `tickSizeInner` when centered between tick lines

![image](https://user-images.githubusercontent.com/8255295/53353613-0e675a80-391d-11e9-9af5-35aa4a8d0e04.png)

2019-02-26 13:44 UTC, ColinEberhardt commented
Thanks for the PR @DevAndyLee looks good. One general question, I'm wondering about the need for `tickOffset`? As illustrated by your example you are using this for situations where the scale step is non-uniform. 

In order to render the ticks / labels it [obtains the array of ticks](https://github.com/d3fc/d3fc/pull/1231/files#diff-0763d5d6d06cd6337117c5c19d980950R79) - can you just use this to determine the location of each label instead?

2019-02-26 13:46 UTC, ColinEberhardt commented on packages/d3fc-chart/README.md
> +The Cartesian chart exposes the [d3fc-axis](https://github.com/d3fc/d3fc/tree/master/packages/d3fc-axis#d3fc-axis) *ticks*, *tickSize*, *tickValue*, *tickFormat*, *tickArguments*, *tickSizeInner*, *t
Thanks for expanding on this list - well spotted!

2019-02-26 14:04 UTC, DevAndyLee commented
> Thanks for the PR @DevAndyLee looks good. One general question, I'm wondering about the need for `tickOffset`? As illustrated by your example you are using this for situations where the scale step is non-uniform.
> 
> In order to render the ticks / labels it [obtains the array of ticks](https://github.com/d3fc/d3fc/pull/1231/files#diff-0763d5d6d06cd6337117c5c19d980950R79) - can you just use this to determine the location of each label instead?

Unfortunately not, or at least I couldn't find a way. The `scale` gives the centre of each tick but not its size, which we need so we can draw the line on the edge. I considered passing `d` to the `step()` function (it would be ignored by `scaleBand` but could be used by a custom scale to give the correct size for each tick). However, it didn't feel right.

2019-02-26 17:25 UTC, chrisprice requested changes

2019-02-26 17:25 UTC, chrisprice commented on packages/d3fc-axis/src/axis.js
> +                        const offset = sign * tickOffset(d);
Should we pass `i` in as well?

2019-02-26 17:25 UTC, chrisprice commented on packages/d3fc-axis/src/axis.js
> +    let centerAlignTicks = false;
I'm not sure about the naming. The convention seems to be a `tick` prefix - maybe we could we go for `tickCenter`/`tickAlign` (with `'center'` as a value)?

2019-02-26 17:25 UTC, chrisprice commented on packages/d3fc-axis/src/axis.js
> +                        const offset = sign * tickOffset(d);
Actually picking up on Colin's question, could we access `ticksArray[i+1]`?

2019-02-26 20:47 UTC, ColinEberhardt commented
> The `scale` gives the centre of each tick but not its size

This is what @chrisprice is referring to when he mentions `ticksArray[i+1]`, we can use this to compute the distance between each tick and position the label.

I've found the D3 [pairs](https://github.com/d3/d3-array#pairs) function quite useful for this sort of thing before.

2019-02-27 09:23 UTC, DevAndyLee commented
![image](https://user-images.githubusercontent.com/8255295/53479614-54cdce00-3a71-11e9-88f8-827dd9e9f447.png)

2019-02-27 20:45 UTC, chrisprice commented
![image](https://user-images.githubusercontent.com/433457/53521599-7dd17b80-3ad0-11e9-933a-ecc9d07ef413.png)

(I like this new way of communicating 😄)

2019-02-27 22:32 UTC, ColinEberhardt commented
Oh, I see your point @DevAndyLee - for continuous scales the calculation based on `tickArray` should be fine, but for ordinal / band scales we actually want to shift the location of the tick.

Solving both is going to require a bit more thought!

2019-02-28 07:35 UTC, chrisprice commented
If my suggestion want too cryptic, does it not solve both?

2019-02-28 09:14 UTC, DevAndyLee commented
The point I was trying to make is that `ticksArray[]` tells you where to put the center of the text, but it doesn't tell you where to put the tick line.

If the distance between the ticks is always the same, then you can just position it half-way between. If the distance changes, then you need another way to work out where to put it.

There are actually lots of ways we could do this...

1. Use a function that can be overridden (as in this PR).

2. Assuming we're using a custom `scale` anyway, add some function to the `scale` that can do this (the `step` property is already specific to point and band scales). e.g. We could use `step(d)` to let the scale vary the step size, or else create a new function.

3. Use a data structure that associates the grouped labels with the underlying domain (as per my original PR - e.g. "Fruit" becomes `{ name: "Fruit", domain: ["Apples", "Bananas"] }`). This is actually a bit more complicated here, because in trying to keep d3fc-axis simple, it no longer has access to the original domain and scale.

2019-02-28 12:27 UTC, ColinEberhardt commented
> If my suggestion want too cryptic, does it not solve both?

I must admit, I didn't quite get it!

Perhaps we should get together and have a chat about it. Definitely more complicated than I had originally anticipated.

2019-03-08 15:11 UTC, closed without merging