Add typescript demonstration for Candlestick type
d3fc/d3fc pull request #1293
Opened 2019-08-07 10:10 UTC by hanna-greaves

Demonstration to get feedback on adding typescript definitions to d3fc. 

Naturally I would like to see us move this library to be written in native Typescript eventually but I am happy writing these definitions in the meantime ;) 

Here's a quick demo of the types being used in a `.ts` environment

![ts](https://user-images.githubusercontent.com/19157374/62614692-d1f44d80-b903-11e9-9828-b99b56431d26.gif)

2019-08-08 08:09 UTC, joelwilliamsmith requested changes

2019-08-08 08:09 UTC, joelwilliamsmith commented on packages/d3fc-shape/src/index.d.ts
> +    (data: CandlestickData[]): void;
Shouldn't this be `string | null` rather than `void`?

2019-08-08 14:25 UTC, ColinEberhardt commented
This looks really cool - thanks @hanna-greaves - I'd be very happy to see a complete set of TypeScript definitions added to the project.

2019-08-12 13:09 UTC, hanna-greaves commented
Thanks for the comments all, I will work on this further and open a proper PR soon :)

2019-08-12 13:09 UTC, closed without merging