feat: add support and example for WebGL cross for point series
d3fc/d3fc pull request #1341
Opened 2019-11-25 15:20 UTC by mattstobbs

2019-11-25 17:13 UTC, chrisprice requested changes

2019-11-25 17:13 UTC, chrisprice commented on packages/d3fc-webgl/src/shaders/fragmentShaderSnippets.js
> +    float innerCornerDistance = min(abs(pointCoordTransform.x), abs(pointCoordTransform.y)) + 0.56;
`0.56` 🤔

2019-11-27 10:54 UTC, mattstobbs commented on packages/d3fc-webgl/src/shaders/fragmentShaderSnippets.js
> +    float innerCornerDistance = min(abs(pointCoordTransform.x), abs(pointCoordTransform.y)) + 0.56;
It should hopefully be more clear now

2019-11-27 14:30 UTC, chrisprice approved these changes

2019-11-27 14:31 UTC, merged