feat: add diamonds webgl point series example
d3fc/d3fc pull request #1423
Opened 2020-01-31 12:33 UTC by OliverForeman

Adds the diamonds example rendering around 54k points

2020-03-16 16:02 UTC, adilparvez approved these changes

2020-04-10 14:30 UTC, chrisprice requested changes
Needs to be brought inline with the new examples format

2020-04-17 09:33 UTC, chrisprice requested changes

2020-04-17 09:33 UTC, chrisprice commented on examples/diamonds/index.js
> +const width = 920;
Should we be defining a fixed width/height?

2020-04-17 09:33 UTC, chrisprice commented on examples/diamonds/index.html
> +<html>
Match the html structure of the other charts

2020-04-17 09:33 UTC, chrisprice commented on examples/diamonds/index.js
> +        fc.pointFill().color([1, 0, 0, 1])(program);
These need updating to match the new API

2020-04-17 09:33 UTC, chrisprice commented on examples/diamonds/index.js
> +            d3.select('d3fc-group')
This should just render the chart

2020-04-20 09:14 UTC, merged