D3fc series examples
d3fc/d3fc pull request #1487
Opened 2020-03-17 09:16 UTC by OliverForeman

The start of moving all examples to the examples directory.

In this PR:
* Area
* Autobandwidth
* Bar
* Box Plot
* Candlestick

Each example is being moved to 3 directories (one for each rendering method), for example `candlestick` examples are now under `series-svg-candlestick`, `series-canvas-candlestick`, and `series-webgl-candlestick`.

Every new directory contains the example files, a README, and a test file that also generates a screenshot for the example. In some cases a screenshot is also generated for the `d3fc-series/screenshots` directory for use on the website.

2020-03-17 11:21 UTC, chrisprice requested changes

2020-03-17 11:21 UTC, chrisprice commented on examples/series-canvas-area/index.js
> +const width = container.clientWidth;
Can we get these from the `measure` event instead?

2020-03-17 11:21 UTC, chrisprice commented on examples/series-canvas-area/index.js
> +canvas.width = width;
This isn't necessary with `d3fc-canvas`

2020-03-17 11:21 UTC, chrisprice commented on examples/series-canvas-autobandwidth/README.md
> +# Series Canvas Autobandwidth
Should the folder be called series-canvas-auto-bandwidth? And this be Series Canvas Auto Bandwidth?

2020-03-17 16:22 UTC, adilparvez approved these changes

2020-03-23 13:40 UTC, chrisprice approved these changes

2020-03-23 13:40 UTC, merged