Webgl point star
d3fc/d3fc pull request #1503
Opened 2020-03-24 14:03 UTC by adilparvez

![image](https://user-images.githubusercontent.com/6894766/77434062-2fc49f80-6dd8-11ea-9133-87d6ae334b74.png)

2020-03-24 14:06 UTC, adilparvez commented
PR looks messed up for some reason, will rebase onto master.

2020-03-25 09:41 UTC, chrisprice requested changes
Seems weird that any package-locks/screenshots should be updated

2020-03-25 10:00 UTC, chrisprice commented
As discussed I really like the idea of distance functions. Please could you raise an issue for moving all of the symbol rendering over to using it? It would be great if you could detail the changes we'd likely want to make to stroke/fill while we're at it.

2020-03-25 13:09 UTC, chrisprice approved these changes

2020-03-25 16:39 UTC, merged